// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Mark Wells <contact@markwells.dev>

//! Config template generation for `catenary config`.

#![allow(clippy::print_stdout, reason = "CLI tool needs to output to stdout")]

/// Annotated recommended config template.
///
/// This is a curated TOML document with comments explaining each entry,
/// not generated from structs. Users redirect this to their config file.
/// The target path depends on `XDG_CONFIG_HOME` (Linux: `~/.config`,
/// macOS: `~/Library/Application Support`, Windows: `AppData/Roaming`).
const TEMPLATE: &str = r#"# Catenary recommended config
# Generated by `catenary config`. Edit to match your workflow.
#
# Config sources (later overrides earlier):
#   1. <XDG_CONFIG_HOME>/catenary/config.toml  (this file)
#   2. .catenary.toml                          (project-local)
#   3. CATENARY_CONFIG env var                 (explicit override)
#
# XDG_CONFIG_HOME defaults:
#   Linux:   ~/.config
#   macOS:   ~/Library/Application Support
#   Windows: C:\Users\<user>\AppData\Roaming

# ── Command filtering ────────────────────────────────────────────
#
# Allowlist-based: only explicitly permitted commands can run.
# Everything else is denied with a dump of the allowed config.
#
# Three states:
#   1. No [commands] section         — not configured (hint notification)
#   2. client_enforcement_only=true  — deliberate opt-out, no enforcement
#   3. allow = [...] present         — active allowlist
#
# Keys:
#   build    — project build tool (e.g., "make"). Set per-project in
#              .catenary.toml so the agent uses the build system.
#   allow    — commands the agent can run unconditionally.
#   pipeline — commands allowed mid-pipeline (reading stdin), denied
#              at pipeline position 0 (reading files directly).
#   deny.*   — subcommand denylist within an allowed command.
#
# Uncomment the [commands] section below to activate.

# [commands]
# # client_enforcement_only = true
# build = "make"
# allow = ["git", "gh", "cp", "rm", "mkdir", "mv", "touch",
#          "chmod", "sleep", "cd", "true", "false", "which"]
# pipeline = ["grep", "head", "tail", "wc", "jq", "awk",
#             "sort", "sed", "tr", "cut", "uniq", "tee"]
#
# [commands.deny]
# git = ["grep", "ls-files", "ls-tree"]
# sqlite3 = ["-cmd"]
#
# # Per-command guidance — optional hints shown when a command is denied.
# # Groups map commands to a message. {READ} and {EDIT} resolve per-client.
#
# [commands.guidance.read]
# message = "Use {READ} instead"
# commands = ["cat", "head", "tail", "less", "more"]
#
# [commands.guidance.edit]
# message = "Use {EDIT} instead"
# commands = ["sed"]
#
# [commands.guidance.scan]
# message = "Use Catenary's grep tool instead"
# commands = ["rg", "ag", "ack", "fd", "grep", "egrep",
#             "fgrep", "rgrep", "zgrep"]
#
# [commands.guidance.list]
# message = "Use Catenary's glob tool instead"
# commands = ["ls", "dir", "tree", "find"]
#
# [commands.guidance.build]
# commands = ["cargo", "rustc", "rustup", "npm", "npx", "yarn",
#             "pnpm", "go", "gradle", "mvn", "cmake", "pip",
#             "poetry", "pytest", "prettier"]

# ── Project-local overrides (.catenary.toml) ─────────────────────
#
# Project config scopes build tools and can replace the user's
# allowlist for a specific workspace. Examples:
#
#   # Set the build tool for this project
#   [commands]
#   build = "make"
#
#   # Replace the user's allowlist for this project
#   [commands]
#   allow = ["git", "gh", "kubectl", "docker"]
#
#   # Disable Catenary LSP for this workspace entirely
#   # (commands config still applies)
#   lsp = false

# ── Notifications ────────────────────────────────────────────────
#
# Controls which events are promoted to user-facing notifications
# via systemMessage. Options: "debug", "info", "warn", "error".

# [notifications]
# threshold = "warn"

# ── Server environment ────────────────────────────────────────────
#
# Per-server environment variables. Added to the inherited
# environment (config value wins on conflict).
#
# [server.rust-analyzer]
# env = { CLIPPY_DISABLE_DOCS_LINKS = "1" }

# ── Root markers ──────────────────────────────────────────────────
#
# Root markers define project boundaries within workspace roots.
# Catenary walks up from each file, stopping at the first directory
# containing any marker. That directory becomes the server's root.
# Different resolved roots get separate server instances.
#
# Defaults are shipped for common languages (rust = ["Cargo.toml"],
# go = ["go.mod"], python = ["pyproject.toml", ...], etc.). Override
# per-language, or disable with an empty list.
#
# Entries can be exact filenames or glob patterns (*, ?, []).
# Exact filenames use a fast exists() check; globs read directory
# entries and match against compiled patterns.
#
# [language.rust]
# root_markers = ["rust-toolchain.toml"]   # custom markers
#
# [language.csharp]
# root_markers = ["*.sln", "*.csproj"]     # glob patterns
#
# [language.python]
# root_markers = []                        # disable for python

# ── Tool budgets ─────────────────────────────────────────────────
#
# Output budgets in characters. Larger budgets give the agent more
# context but consume more of the conversation window.

# [tools.grep]
# budget = 4000

# [tools.glob]
# budget = 2000
# outline_threshold = 200
"#;

/// Print the recommended config template to stdout.
pub fn print_template() {
    print!("{TEMPLATE}");
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    reason = "tests use expect for readable assertions"
)]
mod tests {
    use super::*;

    #[test]
    fn template_is_valid_toml() {
        // The template with all comments is trivially valid TOML (empty doc).
        toml::from_str::<toml::Value>(TEMPLATE).expect("template should be valid TOML");
    }

    #[test]
    fn template_commands_block_is_valid_toml() {
        // Extract the commented-out [commands] block (between "# [commands]"
        // and the next section separator) and verify it parses when uncommented.
        let mut in_block = false;
        let mut lines = Vec::new();
        for line in TEMPLATE.lines() {
            if line == "# [commands]" {
                in_block = true;
            } else if in_block && line.starts_with("# ── ") {
                break;
            }
            if in_block {
                lines.push(
                    line.strip_prefix("# ")
                        .unwrap_or(if line == "#" { "" } else { line }),
                );
            }
        }
        assert!(!lines.is_empty(), "should find commented [commands] block");
        let block = lines.join("\n");
        toml::from_str::<toml::Value>(&block)
            .expect("uncommented [commands] block should be valid TOML");
    }

    #[test]
    fn template_contains_allowlist_keys() {
        assert!(
            TEMPLATE.contains("allow"),
            "template should contain allow key",
        );
        assert!(
            TEMPLATE.contains("pipeline"),
            "template should contain pipeline key",
        );
        assert!(
            TEMPLATE.contains("build"),
            "template should contain build key",
        );
        assert!(
            TEMPLATE.contains("[commands.deny]"),
            "template should contain [commands.deny] section",
        );
    }

    #[test]
    fn template_contains_client_enforcement_only() {
        assert!(
            TEMPLATE.contains("client_enforcement_only"),
            "template should contain client_enforcement_only option",
        );
    }

    #[test]
    fn template_commands_section_commented_out() {
        // The [commands] section should be commented out so users must
        // explicitly uncomment to activate.
        assert!(
            TEMPLATE.contains("# [commands]"),
            "template [commands] section should be commented out",
        );
    }

    #[test]
    fn template_contains_guidance_section() {
        assert!(
            TEMPLATE.contains("[commands.guidance."),
            "template should contain guidance section",
        );
        assert!(
            TEMPLATE.contains("guidance.scan"),
            "template should contain scan guidance group",
        );
        assert!(
            TEMPLATE.contains("guidance.build"),
            "template should contain build guidance group",
        );
    }
}
