// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Mark Wells <contact@markwells.dev>

//! Config template generation for `catenary config`.
//!
//! The built-in server defaults section is generated at runtime from
//! [`crate::config::DEFAULT_SERVERS`] so it stays current across
//! releases.

use crate::cli::Output;

/// Annotated recommended config template.
///
/// This is a curated TOML document with comments explaining each entry,
/// not generated from structs. Users redirect this to their config file.
/// The target path depends on `XDG_CONFIG_HOME` (Linux: `~/.config`,
/// macOS: `~/Library/Application Support`, Windows: `AppData/Roaming`).
const TEMPLATE: &str = r#"# Catenary recommended config
# Generated by `catenary config`. Edit to match your workflow.
#
# Config sources (later overrides earlier):
#   1. <XDG_CONFIG_HOME>/catenary/config.toml  (this file)
#   2. .catenary.toml                          (project-local)
#   3. CATENARY_CONFIG env var                 (explicit override)
#
# XDG_CONFIG_HOME defaults:
#   Linux:   ~/.config
#   macOS:   ~/Library/Application Support
#   Windows: C:\Users\<user>\AppData\Roaming

# ── Command filtering ────────────────────────────────────────────
#
# Allowlist-based: only explicitly permitted commands can run.
# Everything else is denied with a dump of the allowed config.
#
# Three states:
#   1. No [commands] section         — not configured (hint notification)
#   2. client_enforcement_only=true  — deliberate opt-out, no enforcement
#   3. allow = [...] present         — active allowlist
#
# Keys:
#   build    — project build tool (e.g., "make"). Set per-project in
#              .catenary.toml so the agent uses the build system.
#   allow    — commands the agent can run unconditionally.
#   pipeline — commands allowed mid-pipeline (reading stdin), denied
#              at pipeline position 0 (reading files directly).
#   deny.*   — subcommand denylist within an allowed command.
#   allow_file_redirects — permit `>`/`>>`/`2>file` redirects (default
#              false). Redirected writes bypass the tracked Edit/Write
#              path, so the diagnostics batch may be incomplete (it shows
#              fixes for tracked files while the redirected write went
#              unseen). fd-dups (`2>&1`, `>&2`) and device sinks
#              (`/dev/null`, ...) are always allowed regardless.
#
# Uncomment the [commands] section below to activate.

# [commands]
# # client_enforcement_only = true
# # allow_file_redirects = false
# build = "make"
# # `allow` includes read/stdout-only tools (cat, head, less, diff,
# # echo, ...): reads aren't a write vector, and redirected writes
# # (`cat > f`) are caught by the redirect gate, not by blocking cat.
# allow = ["git", "gh", "cp", "rm", "mkdir", "mv", "touch",
#          "chmod", "sleep", "cd", "true", "false", "which",
#          "cat", "head", "tail", "less", "more", "diff",
#          "echo", "printf", "seq"]
# pipeline = ["grep", "wc", "jq", "sort", "tr", "cut", "uniq"]
#
# [commands.deny]
# git = ["grep", "ls-files", "ls-tree"]
# sqlite3 = ["-cmd"]
#
# [commands.deny_flags]
# make = ["-C"]
# cargo = ["--manifest-path"]
#
# # Per-command guidance — optional hints shown when a command is denied.
# # Groups map commands to a message. {EDIT} resolves per-client.
#
# [commands.guidance.edit]
# message = "Use {EDIT} for surgical edits, `catenary sed` for sweeps."
# commands = ["sed"]
#
# [commands.guidance.scan]
# redirect = "grep"
# commands = ["rg", "ag", "ack", "fd", "grep", "egrep",
#             "fgrep", "rgrep", "zgrep"]
#
# [commands.guidance.list]
# redirect = "glob"
# commands = ["ls", "dir", "tree", "find"]
#
# [commands.guidance.build]
# commands = ["cargo", "rustc", "rustup", "npm", "npx", "yarn",
#             "pnpm", "go", "gradle", "mvn", "cmake", "pip",
#             "poetry", "pytest", "prettier"]

# ── Project-local overrides (.catenary.toml) ─────────────────────
#
# A project .catenary.toml honors `build` only. Every other [commands]
# key — client_enforcement_only, allow, pipeline, deny, deny_flags,
# allow_file_redirects — is user-level only: the filter resolves
# daemon-globally (one daemon serves every session), so a project can
# neither relax it nor turn it on/off for itself. Those keys are ignored
# (with a warning) in project config — keep them here in user config.
#
#   # Set the build tool for this project
#   [commands]
#   build = "make"
#
#   # Disable Catenary LSP for this workspace entirely
#   # (the project build tool still applies)
#   lsp = false

# ── Notifications ────────────────────────────────────────────────
#
# Controls which events are promoted to user-facing notifications
# via systemMessage. Options: "debug", "info", "warn", "error".
#
# desktop: OS-level desktop notifications for error events.
# Set to false to suppress. CATENARY_NOTIFY=0 env var also suppresses.

# [notifications]
# threshold = "warn"
# desktop = true

# ── Server environment ────────────────────────────────────────────
#
# Per-server environment variables. Added to the inherited
# environment (config value wins on conflict).
#
# [server.rust-analyzer]
# env = { CLIPPY_DISABLE_DOCS_LINKS = "1" }
#
# # Suppress SymbolKind prefix in glob output. Useful for servers
# # where the symbol name embeds structural context (e.g., H1:, CodeBlock:).
# # The built-in `lattice` markdown default already sets this.
# [server.lattice]
# suppress_symbol_kind = true

# ── Root markers ──────────────────────────────────────────────────
#
# Root markers define project boundaries within workspace roots.
# Catenary walks up from each file, stopping at the first directory
# containing any marker. That directory becomes the server's root.
# Different resolved roots get separate server instances.
#
# Defaults are shipped for common languages (rust = ["Cargo.toml"],
# go = ["go.mod"], python = ["pyproject.toml", ...], etc.). Override
# per-language, or disable with an empty list.
#
# Entries can be exact filenames or glob patterns (*, ?, []).
# Exact filenames use a fast exists() check; globs read directory
# entries and match against compiled patterns.
#
# [language.rust]
# root_markers = ["rust-toolchain.toml"]   # custom markers
#
# [language.csharp]
# root_markers = ["*.sln", "*.csproj"]     # glob patterns
#
# [language.python]
# root_markers = []                        # disable for python

# ── Tool budgets ─────────────────────────────────────────────────
#
# Output budgets in characters. Larger budgets give the agent more
# context but consume more of the conversation window.

# [tools.grep]
# budget = 4000

# [tools.glob]
# budget = 2000
# outline_threshold = 200

# ── Diagnostics (`catenary diagnostics`) ─────────────────────────
#
# diagnostics_per_page: single-shot preview budget. When a run produces
#   more than this many diagnostics, the preview shows the first N (errors
#   before warnings) and the complete set is written to a per-session file
#   under the runtime dir, named in a trailing "… N more — full report at
#   <path>" line. Default: 50.
# diagnostics_severity: the minimum severity that marks a run "dirty"
#   (exit code 1) — one of error, warning, info, hint. Default "error", so
#   the exit code means "does it compile"; warnings still print but exit 0.

# [tools]
# diagnostics_per_page = 50
# diagnostics_severity = "error"
"#;

/// Print the recommended config template to stdout.
///
/// Appends a built-in server defaults reference section generated from
/// the embedded `defaults/servers.toml`.
pub fn print_template(out: &mut Output) {
    let _ = out.write_str(format_args!("{TEMPLATE}"));
    let _ = out.write_str(format_args!("{}", generate_defaults_section()));
}

/// Generate a commented-out reference section listing all built-in
/// server defaults.
///
/// Each `[server.*]` entry from `defaults/servers.toml` is rendered as
/// a comment block so users can discover canonical names and override
/// selectively.
fn generate_defaults_section() -> String {
    use std::fmt::Write;

    let mut out = String::new();
    let _ = writeln!(
        out,
        "\n# ── Built-in Server Defaults ──────────────────────────────────"
    );
    let _ = writeln!(
        out,
        "# Catenary ships default definitions for these servers. Reference"
    );
    let _ = writeln!(
        out,
        "# one by name in a [language.*] servers list and it works without"
    );
    let _ = writeln!(
        out,
        "# a [server.*] entry. To override, uncomment and modify."
    );

    for line in crate::config::DEFAULT_SERVERS.lines() {
        if line.is_empty() {
            let _ = writeln!(out, "#");
        } else if line.starts_with('#') {
            // Preserve original comment lines (section headers).
            let _ = writeln!(out, "# {line}");
        } else {
            let _ = writeln!(out, "# {line}");
        }
    }

    out
}

/// Test-only access to the recommended `[commands]` config embedded in
/// [`TEMPLATE`]. The single source of truth for the shipped default
/// command-filter config: this module's own tests *and* `command_filter`'s
/// behavioral tests both derive from it, so neither hand-maintains a mirror
/// that could drift from the template.
#[cfg(test)]
#[allow(
    clippy::expect_used,
    reason = "test-only helper; expect gives a readable failure"
)]
pub(crate) mod test_recommended {
    use crate::config::CommandsConfig;

    /// The commented-out `[commands]` block from [`super::TEMPLATE`] (between
    /// `# [commands]` and the next section separator), uncommented.
    pub fn block() -> String {
        let mut in_block = false;
        let mut lines = Vec::new();
        for line in super::TEMPLATE.lines() {
            if line == "# [commands]" {
                in_block = true;
            } else if in_block && line.starts_with("# ── ") {
                break;
            }
            if in_block {
                lines.push(
                    line.strip_prefix("# ")
                        .unwrap_or(if line == "#" { "" } else { line }),
                );
            }
        }
        lines.join("\n")
    }

    /// Parse the recommended `[commands]` block into a [`CommandsConfig`].
    pub fn config() -> CommandsConfig {
        #[derive(serde::Deserialize)]
        struct Wrapper {
            commands: CommandsConfig,
        }
        let wrapper: Wrapper =
            toml::from_str(&block()).expect("recommended [commands] block is valid TOML");
        wrapper.commands
    }
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::literal_string_with_formatting_args,
    reason = "tests use expect for readable assertions; {EDIT} is a template var, not a format arg"
)]
mod tests {
    use super::*;

    #[test]
    fn template_is_valid_toml() {
        // The template with all comments is trivially valid TOML (empty doc).
        toml::from_str::<toml::Value>(TEMPLATE).expect("template should be valid TOML");
    }

    #[test]
    fn template_commands_block_is_valid_toml() {
        // The commented-out [commands] block should parse when uncommented.
        let block = test_recommended::block();
        assert!(!block.is_empty(), "should find commented [commands] block");
        toml::from_str::<toml::Value>(&block)
            .expect("uncommented [commands] block should be valid TOML");
    }

    #[test]
    fn template_pipeline_drops_awk_and_sed() {
        // awk and sed are interpreters whose program string is a quoted
        // argument the filter quote-masks before parsing, so it can't see
        // their in-band exec/write side effects (awk system()/print>, sed
        // -i/w, GNU sed e). Same unparseable hazard python is denied for, so
        // they are dropped from the recommended pipeline (bugs/12 / Decision
        // 6). The mass-edit slice is rehomed onto `catenary sed`.
        let pipeline = test_recommended::config()
            .pipeline
            .expect("recommended config has a pipeline list");
        let has = |c: &str| pipeline.iter().any(|p| p == c);
        assert!(!has("awk"), "pipeline should not include awk");
        assert!(!has("sed"), "pipeline should not include sed");
        // Pure filters that cannot exec/write stay.
        assert!(has("cut"), "cut stays in pipeline");
        assert!(has("jq"), "jq stays in pipeline");
        assert!(has("grep"), "grep stays in pipeline");
    }

    #[test]
    fn template_edit_guidance_points_to_catenary_sed() {
        // With sed out of the pipeline it is denied at every position, so the
        // edit guidance always fires. It names both surfaces: the host edit
        // tool for surgical edits and `catenary sed` for sweeps (the redirect
        // that makes the removal a rehome, not a capability loss).
        let guidance = test_recommended::config()
            .guidance
            .expect("recommended config has guidance groups");
        let edit = guidance.get("edit").expect("edit guidance group");
        let msg = edit
            .message
            .as_deref()
            .expect("edit guidance group has a message");
        assert!(
            msg.contains("catenary sed"),
            "edit guidance should name catenary sed: {msg:?}",
        );
        assert!(
            msg.contains("{EDIT}"),
            "edit guidance should keep the per-client edit-tool template var: {msg:?}",
        );
    }

    #[test]
    fn template_contains_allowlist_keys() {
        assert!(
            TEMPLATE.contains("allow"),
            "template should contain allow key",
        );
        assert!(
            TEMPLATE.contains("pipeline"),
            "template should contain pipeline key",
        );
        assert!(
            TEMPLATE.contains("build"),
            "template should contain build key",
        );
        assert!(
            TEMPLATE.contains("[commands.deny]"),
            "template should contain [commands.deny] section",
        );
        assert!(
            TEMPLATE.contains("[commands.deny_flags]"),
            "template should contain [commands.deny_flags] section",
        );
    }

    #[test]
    fn template_documents_allow_file_redirects() {
        assert!(
            TEMPLATE.contains("allow_file_redirects"),
            "template should document the allow_file_redirects flag",
        );
    }

    #[test]
    fn template_pipeline_drops_tee() {
        // `tee` writes its file operand directly — a write vector that
        // bypasses Edit/Write — so it is not in the default pipeline.
        assert!(
            !TEMPLATE.contains("\"tee\""),
            "template pipeline should not include tee",
        );
    }

    #[test]
    fn template_allows_reads() {
        // Decision 7: read/stdout-only tools live in `allow` (no enforcement
        // rationale to block reads under the stateless editing model).
        let allow = test_recommended::config()
            .allow
            .expect("recommended config has an allow list");
        for cmd in [
            "cat", "head", "tail", "less", "more", "diff", "echo", "printf", "seq",
        ] {
            assert!(
                allow.iter().any(|c| c == cmd),
                "recommended allow should contain {cmd}",
            );
        }
    }

    #[test]
    fn template_drops_read_guidance() {
        // The vestigial read-blocking guidance group is removed (Decision 7) —
        // no `guidance.read` and no "Use {READ}" message path in the default.
        assert!(
            !TEMPLATE.contains("guidance.read"),
            "template should not define a read guidance group",
        );
        assert!(
            !TEMPLATE.contains("{READ}"),
            "template should not reference the {{READ}} template var",
        );
        if let Some(guidance) = test_recommended::config().guidance {
            assert!(
                !guidance.contains_key("read"),
                "recommended config should have no read guidance group",
            );
        }
    }

    #[test]
    fn template_contains_client_enforcement_only() {
        assert!(
            TEMPLATE.contains("client_enforcement_only"),
            "template should contain client_enforcement_only option",
        );
    }

    #[test]
    fn template_commands_section_commented_out() {
        // The [commands] section should be commented out so users must
        // explicitly uncomment to activate.
        assert!(
            TEMPLATE.contains("# [commands]"),
            "template [commands] section should be commented out",
        );
    }

    #[test]
    fn template_contains_guidance_section() {
        assert!(
            TEMPLATE.contains("[commands.guidance."),
            "template should contain guidance section",
        );
        assert!(
            TEMPLATE.contains("guidance.scan"),
            "template should contain scan guidance group",
        );
        assert!(
            TEMPLATE.contains("guidance.build"),
            "template should contain build guidance group",
        );
    }

    #[test]
    fn template_defaults_section_contains_all_servers() {
        let section = generate_defaults_section();
        // Every [server.*] key from defaults/servers.toml must appear.
        let expected = [
            "rust-analyzer",
            "gopls",
            "clangd",
            "zls",
            "pyright",
            "taplo",
            "lattice",
            "marksman",
            "intelephense",
            "vscode-css",
            "vscode-html",
            "vscode-json",
            "vscode-eslint",
            "bash-ls",
            "haskell-ls",
            "typescript-ls",
            "lua-ls",
            "vim-ls",
            "yaml-ls",
            "ansible-ls",
            "cmake-ls",
            "sql-ls",
            "docker-ls",
            "csharp-ls",
            "fsautocomplete",
            "kotlin-ls",
            "ocamllsp",
            "elm-ls",
            "svelte-ls",
            "nil",
            "terraform-ls",
            "sourcekit-lsp",
            "metals",
            "dart-ls",
            "julia-ls",
            "r-ls",
        ];
        for name in expected {
            assert!(
                section.contains(name),
                "defaults section should contain server '{name}'",
            );
        }
    }

    #[test]
    fn template_defaults_section_all_commented() {
        let section = generate_defaults_section();
        for line in section.lines() {
            assert!(
                line.is_empty() || line.starts_with('#'),
                "defaults section line should be a comment: {line:?}",
            );
        }
    }
}
