// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Mark Wells <contact@markwells.dev>

//! Always-on service management: install Catenary's daemon under the host's
//! per-user service manager (ws49-04).
//!
//! Under the hooks-only lifecycle the daemon no longer self-exits on an idle
//! last-client disconnect (that path retired in `router.rs` with this ticket);
//! its lifetime belongs to a service manager instead. This module installs,
//! removes, and reports on that unit:
//!
//! - **Linux** — a systemd `--user` unit at
//!   `$XDG_CONFIG_HOME/systemd/user/catenary.service`, enabled and started via
//!   `systemctl --user`.
//! - **macOS** — a per-user launchd `LaunchAgent` plist at
//!   `~/Library/LaunchAgents/dev.markwells.catenary.plist`, loaded via
//!   `launchctl`.
//!
//! Both carry `MALLOC_ARENA_MAX=2`: the ws49-02 arena receipt measured ~82 of
//! 94 MiB retained in glibc arenas after a small-allocation free (bug 136's
//! protocol-churn class), so capping the arena count bounds the resident set an
//! always-on daemon accretes. The unit/plist body carries that citation.
//!
//! The unit/plist *content* is generated by pure, platform-independent
//! functions ([`systemd_unit`], [`launchd_plist`]) so it is unit-testable on any
//! host; the install/uninstall/status/state entry points are whole-function
//! platform splits (never inner-cfg fallbacks — the ws49-01/02 macOS-clippy
//! lesson) so each platform carries exactly one real body.

use std::path::PathBuf;

use anyhow::Result;

use crate::cli::Output;

/// The systemd `--user` unit file name (Linux).
pub const SYSTEMD_UNIT_NAME: &str = "catenary.service";

/// The launchd `LaunchAgent` label / plist basename (macOS).
pub const LAUNCHD_LABEL: &str = "dev.markwells.catenary";

/// The arena-cap environment variable both units carry (bug 136 lean 3).
pub const ARENA_ENV_KEY: &str = "MALLOC_ARENA_MAX";

/// The arena-cap value: two arenas (the ws49-02 receipt's cap).
pub const ARENA_ENV_VALUE: &str = "2";

/// Renders the systemd `--user` unit body for the daemon at `exe` (Linux).
///
/// Pure and platform-independent so the content is unit-testable anywhere. The
/// `[Service]` block runs `<exe> daemon` in the foreground (`Type=simple`:
/// `catenary daemon` blocks on its accept loop and does not fork), carries the
/// arena cap with its measured citation, and restarts on failure — the service
/// manager, not the daemon, now owns the lifetime.
#[must_use]
pub fn systemd_unit(exe: &str) -> String {
    format!(
        "[Unit]\n\
         Description=Catenary code-intelligence daemon\n\
         Documentation=https://github.com/TwoWells/Catenary\n\
         After=default.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={exe} daemon\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         # Arena cap (bug 136 lean 3). The ws49-02 arena receipt measured\n\
         # ~82 of 94 MiB retained in glibc arenas after a small-allocation\n\
         # free (the protocol-churn class bug 136 diagnosed); capping the\n\
         # arena count bounds the resident set an always-on daemon accretes.\n\
         Environment={ARENA_ENV_KEY}={ARENA_ENV_VALUE}\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
    )
}

/// Renders the launchd `LaunchAgent` plist body for the daemon at `exe` (macOS).
///
/// Pure and platform-independent so the content is unit-testable on Linux (this
/// worker's host). `RunAtLoad` + `KeepAlive` make launchd own the lifetime —
/// the daemon is (re)started when the agent loads and kept resident. The
/// `EnvironmentVariables` dict carries the arena cap with its measured citation
/// in a leading comment.
#[must_use]
pub fn launchd_plist(exe: &str) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \
         \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <!-- {ARENA_ENV_KEY}={ARENA_ENV_VALUE}: bug 136 lean 3. The ws49-02\n\
              arena receipt measured ~82 of 94 MiB retained in glibc arenas\n\
              after a small-allocation free; the cap bounds the resident set\n\
              an always-on daemon accretes. -->\n\
         <plist version=\"1.0\">\n\
         <dict>\n\
         \t<key>Label</key>\n\
         \t<string>{LAUNCHD_LABEL}</string>\n\
         \t<key>ProgramArguments</key>\n\
         \t<array>\n\
         \t\t<string>{exe}</string>\n\
         \t\t<string>daemon</string>\n\
         \t</array>\n\
         \t<key>EnvironmentVariables</key>\n\
         \t<dict>\n\
         \t\t<key>{ARENA_ENV_KEY}</key>\n\
         \t\t<string>{ARENA_ENV_VALUE}</string>\n\
         \t</dict>\n\
         \t<key>RunAtLoad</key>\n\
         \t<true/>\n\
         \t<key>KeepAlive</key>\n\
         \t<true/>\n\
         </dict>\n\
         </plist>\n",
    )
}

/// The systemd `--user` unit path: `$XDG_CONFIG_HOME/systemd/user/catenary.service`.
///
/// Resolved through [`crate::paths::config_dir`], so an `isolate_env`-driven
/// test writes under its isolated config base — never the operator's real
/// `~/.config/systemd`.
#[must_use]
pub fn systemd_unit_path() -> PathBuf {
    crate::paths::config_dir()
        .join("systemd")
        .join("user")
        .join(SYSTEMD_UNIT_NAME)
}

/// The launchd `LaunchAgent` plist path: `~/Library/LaunchAgents/<label>.plist`.
///
/// Resolved through [`crate::paths::home_dir`], so an `isolate_env` test — which
/// points `CATENARY_HOME_DIR` at an isolated home base — never touches the
/// operator's real `~/Library`, while production lands on the real `$HOME`. The
/// `LaunchAgents` layout is fixed by launchd, so the isolation hangs it under
/// the isolated home's `Library/LaunchAgents`.
#[must_use]
pub fn launchd_plist_path() -> PathBuf {
    launchd_home()
        .join("Library")
        .join("LaunchAgents")
        .join(format!("{LAUNCHD_LABEL}.plist"))
}

/// The base directory that holds `Library/LaunchAgents` for the plist.
///
/// The home base, one resolver for every home-rooted artifact (misc 229): it
/// used to ride the *data* base's `CATENARY_DATA_DIR` override, which isolated
/// the plist correctly but spelled "home" as "data" — a mislocation the distinct
/// bases exist to catch. Kept private — callers use [`launchd_plist_path`].
fn launchd_home() -> PathBuf {
    crate::paths::home_dir().unwrap_or_else(|| PathBuf::from("."))
}

/// The absolute path to the currently-running `catenary` binary, for `ExecStart`
/// / `ProgramArguments`.
///
/// # Errors
///
/// Returns an error if the current executable path cannot be resolved.
fn daemon_exe() -> Result<String> {
    let exe =
        std::env::current_exe().map_err(|e| anyhow::anyhow!("resolve current executable: {e}"))?;
    Ok(exe.display().to_string())
}

/// A daemon's idle resident-set size in bytes, read by pid (Linux).
///
/// The ws49-02 helper's method (`/proc/<pid>/statm`, resident pages × 4 KiB),
/// parameterized by pid so `catenary doctor` — a separate process from the
/// daemon — can read the *daemon's* footprint. `None` when the pid has no
/// readable `statm` (dead, or racing teardown). Whole-function platform split
/// per the ws49-01/02 macOS-clippy lesson: the non-Linux body is a `const fn`
/// returning `None`, never an inner-cfg fallback.
#[cfg(target_os = "linux")]
#[must_use]
pub fn idle_footprint_bytes(pid: u32) -> Option<u64> {
    let statm = std::fs::read_to_string(format!("/proc/{pid}/statm")).ok()?;
    let resident_pages: u64 = statm.split_whitespace().nth(1)?.parse().ok()?;
    Some(resident_pages * 4096)
}

/// A daemon's idle resident-set size in bytes, read by pid (non-Linux).
///
/// `None` off Linux: no `/proc/<pid>/statm`. Whole-function platform split (a
/// `const fn` stub, not an inner-cfg fallback) so the macOS clippy leg sees a
/// single real body per platform (the ws49-01/02 lesson).
#[cfg(not(target_os = "linux"))]
#[must_use]
pub const fn idle_footprint_bytes(_pid: u32) -> Option<u64> {
    None
}

/// Whether the service unit/plist file is installed on disk (platform-dispatched).
///
/// Linux checks the systemd unit path; macOS checks the launchd plist path.
/// Content-only: it reports the file's presence, not whether the manager has it
/// loaded (that is [`running_state`]).
#[cfg(target_os = "linux")]
#[must_use]
pub fn is_installed() -> bool {
    systemd_unit_path().is_file()
}

/// Whether the service plist is installed on disk (macOS).
#[cfg(target_os = "macos")]
#[must_use]
pub fn is_installed() -> bool {
    launchd_plist_path().is_file()
}

/// Whether the service is installed (other platforms — never).
#[cfg(not(any(target_os = "linux", target_os = "macos")))]
#[must_use]
pub const fn is_installed() -> bool {
    false
}

/// Install and start the always-on service (Linux).
///
/// Writes the systemd `--user` unit under the isolated/real config base, then
/// `systemctl --user daemon-reload`, `enable`, and `start`. The `systemctl`
/// legs are best-effort-reported: on a host without a running user manager
/// (a CI sandbox, a headless box with no user bus) the unit is still written
/// and the failure is surfaced, not swallowed — the live leg is environment-
/// gated, the file leg always lands.
///
/// # Errors
///
/// Returns an error if the unit file cannot be written.
#[cfg(target_os = "linux")]
pub fn install(out: &mut Output) -> Result<()> {
    let exe = daemon_exe()?;
    let unit = systemd_unit(&exe);
    let path = systemd_unit_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| anyhow::anyhow!("create unit directory {}: {e}", parent.display()))?;
    }
    std::fs::write(&path, &unit)
        .map_err(|e| anyhow::anyhow!("write unit {}: {e}", path.display()))?;
    let _ = out.writeln(format_args!("Wrote {}", path.display()));

    // Enable + start via the user manager. Reported, not fatal: the unit file
    // is the durable artifact; a sandbox with no user bus still gets it.
    run_systemctl(out, &["daemon-reload"]);
    run_systemctl(out, &["enable", SYSTEMD_UNIT_NAME]);
    run_systemctl(out, &["start", SYSTEMD_UNIT_NAME]);
    let _ = out.writeln(format_args!(
        "Catenary service installed. `catenary service status` to check it."
    ));
    Ok(())
}

/// Install and load the always-on service (macOS).
///
/// Writes the `LaunchAgent` plist under the isolated/real base, then
/// `launchctl load`. Reported, not fatal — the plist is the durable artifact.
///
/// # Errors
///
/// Returns an error if the plist file cannot be written.
#[cfg(target_os = "macos")]
pub fn install(out: &mut Output) -> Result<()> {
    let exe = daemon_exe()?;
    let plist = launchd_plist(&exe);
    let path = launchd_plist_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            anyhow::anyhow!("create LaunchAgents directory {}: {e}", parent.display())
        })?;
    }
    std::fs::write(&path, &plist)
        .map_err(|e| anyhow::anyhow!("write plist {}: {e}", path.display()))?;
    let _ = out.writeln(format_args!("Wrote {}", path.display()));

    run_launchctl(out, &["load", &path.display().to_string()]);
    let _ = out.writeln(format_args!(
        "Catenary service installed. `catenary service status` to check it."
    ));
    Ok(())
}

/// Install the always-on service (unsupported platforms).
///
/// # Errors
///
/// Always returns an error — no per-user service manager is wired for this
/// platform.
#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub fn install(_out: &mut Output) -> Result<()> {
    Err(anyhow::anyhow!(
        "catenary service is only supported on Linux (systemd --user) and macOS (launchd)"
    ))
}

/// Stop and remove the always-on service (Linux).
///
/// `systemctl --user stop` + `disable`, then removes the unit file and reloads.
/// Idempotent: a missing unit file is not an error, and the `systemctl` legs
/// are reported-not-fatal.
///
/// # Errors
///
/// Returns an error only if an existing unit file cannot be removed.
#[cfg(target_os = "linux")]
pub fn uninstall(out: &mut Output) -> Result<()> {
    run_systemctl(out, &["stop", SYSTEMD_UNIT_NAME]);
    run_systemctl(out, &["disable", SYSTEMD_UNIT_NAME]);
    let path = systemd_unit_path();
    if path.exists() {
        std::fs::remove_file(&path)
            .map_err(|e| anyhow::anyhow!("remove unit {}: {e}", path.display()))?;
        let _ = out.writeln(format_args!("Removed {}", path.display()));
    } else {
        let _ = out.writeln(format_args!(
            "No unit at {} (already removed)",
            path.display()
        ));
    }
    run_systemctl(out, &["daemon-reload"]);
    let _ = out.writeln(format_args!("Catenary service uninstalled."));
    Ok(())
}

/// Unload and remove the always-on service (macOS).
///
/// `launchctl unload`, then removes the plist. Idempotent — a missing plist is
/// not an error.
///
/// # Errors
///
/// Returns an error only if an existing plist file cannot be removed.
#[cfg(target_os = "macos")]
pub fn uninstall(out: &mut Output) -> Result<()> {
    let path = launchd_plist_path();
    if path.exists() {
        run_launchctl(out, &["unload", &path.display().to_string()]);
        std::fs::remove_file(&path)
            .map_err(|e| anyhow::anyhow!("remove plist {}: {e}", path.display()))?;
        let _ = out.writeln(format_args!("Removed {}", path.display()));
    } else {
        let _ = out.writeln(format_args!(
            "No plist at {} (already removed)",
            path.display()
        ));
    }
    let _ = out.writeln(format_args!("Catenary service uninstalled."));
    Ok(())
}

/// Uninstall the always-on service (unsupported platforms).
///
/// # Errors
///
/// Always returns an error — no per-user service manager is wired here.
#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub fn uninstall(_out: &mut Output) -> Result<()> {
    Err(anyhow::anyhow!(
        "catenary service is only supported on Linux (systemd --user) and macOS (launchd)"
    ))
}

/// Print the service's honest state in both installed and absent cases
/// (platform-dispatched).
///
/// Names the manager, the unit/plist path, whether it is installed, and — best
/// effort — whether the manager reports it active. The active check rides the
/// manager's own query (`systemctl --user is-active` / `launchctl list`); its
/// unavailability (no user bus) is reported as "unknown", never faked.
///
/// # Errors
///
/// Never fails — status is a read.
#[cfg(target_os = "linux")]
pub fn status(out: &mut Output) -> Result<()> {
    let path = systemd_unit_path();
    let _ = out.writeln(format_args!("Manager:   systemd --user"));
    let _ = out.writeln(format_args!("Unit:      {}", path.display()));
    if is_installed() {
        let _ = out.writeln(format_args!("Installed: yes"));
        let active = systemctl_is_active();
        let _ = out.writeln(format_args!(
            "Active:    {}",
            active.as_deref().unwrap_or("unknown")
        ));
    } else {
        let _ = out.writeln(format_args!("Installed: no"));
        let _ = out.writeln(format_args!(
            "Run `catenary service install` to run the daemon under systemd."
        ));
    }
    Ok(())
}

/// Print the service's honest state (macOS).
///
/// # Errors
///
/// Never fails — status is a read.
#[cfg(target_os = "macos")]
pub fn status(out: &mut Output) -> Result<()> {
    let path = launchd_plist_path();
    let _ = out.writeln(format_args!("Manager:   launchd (LaunchAgent)"));
    let _ = out.writeln(format_args!("Plist:     {}", path.display()));
    if is_installed() {
        let _ = out.writeln(format_args!("Installed: yes"));
        let active = launchctl_is_loaded();
        let _ = out.writeln(format_args!(
            "Loaded:    {}",
            active.as_deref().unwrap_or("unknown")
        ));
    } else {
        let _ = out.writeln(format_args!("Installed: no"));
        let _ = out.writeln(format_args!(
            "Run `catenary service install` to run the daemon under launchd."
        ));
    }
    Ok(())
}

/// Print the service's honest state (unsupported platforms).
///
/// # Errors
///
/// Never fails — status is a read.
#[cfg(not(any(target_os = "linux", target_os = "macos")))]
pub fn status(out: &mut Output) -> Result<()> {
    let _ = out.writeln(format_args!(
        "catenary service is only supported on Linux (systemd --user) and macOS (launchd)"
    ));
    Ok(())
}

/// The service-manager label for the doctor line (platform-dispatched).
#[cfg(target_os = "linux")]
#[must_use]
pub const fn manager_label() -> &'static str {
    "systemd --user"
}

/// The service-manager label for the doctor line (macOS).
#[cfg(target_os = "macos")]
#[must_use]
pub const fn manager_label() -> &'static str {
    "launchd (LaunchAgent)"
}

/// The service-manager label for the doctor line (unsupported platforms).
#[cfg(not(any(target_os = "linux", target_os = "macos")))]
#[must_use]
pub const fn manager_label() -> &'static str {
    "unsupported"
}

/// The manager's active/loaded state, or `None` when unknowable (Linux).
///
/// Shells to `systemctl --user is-active`. `None` when the query itself cannot
/// run (no user bus, no `systemctl`), so the doctor/status line can say
/// "unknown" honestly rather than fabricate "inactive".
#[cfg(target_os = "linux")]
fn systemctl_is_active() -> Option<String> {
    let out = std::process::Command::new("systemctl")
        .args(["--user", "is-active", SYSTEMD_UNIT_NAME])
        .stdin(std::process::Stdio::null())
        .output()
        .ok()?;
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    (!s.is_empty()).then_some(s)
}

/// Whether the `LaunchAgent` is loaded, or `None` when unknowable (macOS).
///
/// Shells to `launchctl list <label>`: exit 0 means loaded, non-zero means not.
/// `None` when `launchctl` cannot run at all.
#[cfg(target_os = "macos")]
fn launchctl_is_loaded() -> Option<String> {
    let out = std::process::Command::new("launchctl")
        .args(["list", LAUNCHD_LABEL])
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .ok()?;
    Some(if out.success() { "yes" } else { "no" }.to_string())
}

/// Runs `systemctl --user <args>`, reporting the outcome (Linux).
///
/// Best-effort: a failure (no user bus, no `systemctl`) is reported on `out`,
/// never fatal — the unit file is the durable artifact, the live leg is
/// environment-gated (CI sandboxes lack a user manager).
#[cfg(target_os = "linux")]
fn run_systemctl(out: &mut Output, args: &[&str]) {
    let mut full = vec!["--user"];
    full.extend_from_slice(args);
    match std::process::Command::new("systemctl")
        .args(&full)
        .stdin(std::process::Stdio::null())
        .output()
    {
        Ok(o) if o.status.success() => {}
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            let _ = out.writeln(format_args!(
                "note: `systemctl --user {}` did not succeed ({}) — the unit \
                 file is written; run it yourself once a user manager is available",
                args.join(" "),
                stderr.trim(),
            ));
        }
        Err(e) => {
            let _ = out.writeln(format_args!(
                "note: could not run `systemctl --user {}` ({e}) — the unit file \
                 is written; the live leg is environment-gated",
                args.join(" "),
            ));
        }
    }
}

/// Runs `launchctl <args>`, reporting the outcome (macOS).
#[cfg(target_os = "macos")]
fn run_launchctl(out: &mut Output, args: &[&str]) {
    match std::process::Command::new("launchctl")
        .args(args)
        .stdin(std::process::Stdio::null())
        .output()
    {
        Ok(o) if o.status.success() => {}
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            let _ = out.writeln(format_args!(
                "note: `launchctl {}` did not succeed ({}) — the plist is written",
                args.join(" "),
                stderr.trim(),
            ));
        }
        Err(e) => {
            let _ = out.writeln(format_args!(
                "note: could not run `launchctl {}` ({e}) — the plist is written",
                args.join(" "),
            ));
        }
    }
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    reason = "tests use expect for readable assertions"
)]
mod tests {
    use super::*;

    // ── systemd unit content (Linux + portable — the content is host-agnostic) ──

    #[test]
    fn systemd_unit_carries_exec_start_and_arena_cap() {
        let unit = systemd_unit("/usr/local/bin/catenary");
        assert!(
            unit.contains("ExecStart=/usr/local/bin/catenary daemon"),
            "unit must exec `<exe> daemon`:\n{unit}",
        );
        assert!(
            unit.contains("Environment=MALLOC_ARENA_MAX=2"),
            "unit must carry the arena cap:\n{unit}",
        );
    }

    #[test]
    fn systemd_unit_cites_the_arena_receipt() {
        // The measured evidence (ws49-02) must ride in the file as a comment.
        let unit = systemd_unit("/x/catenary");
        assert!(
            unit.contains("82 of 94 MiB"),
            "unit must cite the ws49-02 arena receipt:\n{unit}",
        );
        assert!(
            unit.contains("bug 136"),
            "unit must cite bug 136 (the retention diagnosis):\n{unit}",
        );
    }

    #[test]
    fn systemd_unit_is_a_service_with_install_section() {
        let unit = systemd_unit("/x/catenary");
        assert!(unit.contains("[Unit]"), "has [Unit]:\n{unit}");
        assert!(unit.contains("[Service]"), "has [Service]:\n{unit}");
        assert!(unit.contains("[Install]"), "has [Install]:\n{unit}");
        assert!(unit.contains("Type=simple"), "simple type:\n{unit}");
        assert!(
            unit.contains("WantedBy=default.target"),
            "install target:\n{unit}",
        );
    }

    // ── launchd plist content (macOS half — content-only, per the honesty bar) ──

    #[test]
    fn launchd_plist_carries_program_args_and_arena_cap() {
        let plist = launchd_plist("/opt/homebrew/bin/catenary");
        assert!(
            plist.contains("<string>/opt/homebrew/bin/catenary</string>"),
            "plist must name the exe:\n{plist}",
        );
        assert!(
            plist.contains("<string>daemon</string>"),
            "plist must pass the `daemon` arg:\n{plist}",
        );
        assert!(
            plist.contains("<key>MALLOC_ARENA_MAX</key>"),
            "plist must carry the arena-cap key:\n{plist}",
        );
        assert!(
            plist.contains("<string>2</string>"),
            "plist must carry the arena-cap value:\n{plist}",
        );
    }

    #[test]
    fn launchd_plist_is_keepalive_runatload_with_label() {
        let plist = launchd_plist("/x/catenary");
        assert!(
            plist.contains(&format!("<string>{LAUNCHD_LABEL}</string>")),
            "plist must carry the label:\n{plist}",
        );
        assert!(
            plist.contains("<key>RunAtLoad</key>"),
            "RunAtLoad:\n{plist}"
        );
        assert!(
            plist.contains("<key>KeepAlive</key>"),
            "KeepAlive:\n{plist}"
        );
    }

    #[test]
    fn launchd_plist_cites_the_arena_receipt() {
        let plist = launchd_plist("/x/catenary");
        assert!(
            plist.contains("82 of 94 MiB"),
            "plist must cite the ws49-02 arena receipt:\n{plist}",
        );
    }

    #[test]
    fn launchd_plist_is_well_formed_xml_scaffolding() {
        let plist = launchd_plist("/x/catenary");
        assert!(plist.starts_with("<?xml"), "xml prologue:\n{plist}");
        assert!(
            plist.contains("<plist version=\"1.0\">"),
            "plist open:\n{plist}"
        );
        assert!(
            plist.trim_end().ends_with("</plist>"),
            "plist close:\n{plist}"
        );
    }

    // ── path isolation: an isolate_env test never touches the real homes ──

    #[test]
    fn systemd_unit_path_is_under_config_base() {
        // Under the process's config base (isolate_env points CATENARY_CONFIG_DIR
        // at an isolated subdir); the layout is fixed as systemd/user/.
        let path = systemd_unit_path();
        assert!(
            path.ends_with("systemd/user/catenary.service"),
            "unexpected unit path: {}",
            path.display(),
        );
    }

    #[test]
    fn launchd_plist_path_is_under_library_launchagents() {
        let path = launchd_plist_path();
        assert!(
            path.ends_with(format!("Library/LaunchAgents/{LAUNCHD_LABEL}.plist")),
            "unexpected plist path: {}",
            path.display(),
        );
    }
}
